#!/bin/python3

import math
import os
import random
import re
import sys


def breakingRecords(scores):
    max_record = scores[0]
    min_record = scores[0]
    
    max_breaks = 0
    min_breaks = 0
    
    for i in range(1, len(scores)):
        if scores[i] > max_record:
            max_record = scores[i]
            max_breaks += 1
        elif scores[i] < min_record:
            min_record = scores[i]
            min_breaks += 1
            
    return [max_breaks, min_breaks]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()

