#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dayOfProgrammer' function below.
#
# The function is expected to return a STRING.
# The function accepts INTEGER year as parameter.
#

def dayOfProgrammer(year):
    # Case 1: The Transition Year (1918)
    # February was shortened by 13 days, pushing the 256th day to Sep 26th.
    if year == 1918:
        return "26.09.1918"
    
    # Check for Leap Year status
    is_leap = False
    
    if year < 1918:
        # Case 2: Julian Calendar (Before 1918)
        # Leap year is any year divisible by 4
        if year % 4 == 0:
            is_leap = True
    else:
        # Case 3: Gregorian Calendar (After 1918)
        # Leap year is divisible by 400 OR (divisible by 4 and not 100)
        if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
            is_leap = True
            
    # In a leap year, the 256th day is Sep 12th. Otherwise, it is Sep 13th.
    if is_leap:
        return f"12.09.{year}"
    else:
        return f"13.09.{year}"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()


